name: Get new tag
description: Generate new tag and sets it to env $IMAGE_VERSION
runs:
  using: "composite"
  steps:
    - if: ${{ github.base_ref == 'main' ||  github.base_ref == 'release' }}
      run: git fetch --tags
      shell: bash

    - if: ${{ github.ref_name == 'dev' }}
      run: echo "IMAGE_VERSION=dev-$(date +'%s')" >> $GITHUB_ENV
      shell: bash

    - if: ${{ github.base_ref == 'release' }}
      run: echo "IMAGE_VERSION=$((git tag | egrep rc-[0-9] || echo rc-0 ) | sort --version-sort -r | head -1 | awk -F 'rc-' '{ print "rc-" $2 +1}')" >> $GITHUB_ENV
      shell: bash

    - if: ${{ github.base_ref == 'main' }}
      run: echo "IMAGE_VERSION=$((git tag | egrep v[0-9]\.[0-9]\.[0-9] || echo v1.0.-1 ) | sort --version-sort -r | head -1 | awk -F. -v OFS=. '{$NF++;print}')" >> $GITHUB_ENV
      shell: bash

    - if: ${{ startsWith(github.ref_name, 'rc-') || startsWith(github.ref_name, 'v') }}
      run: echo "IMAGE_VERSION=${{ github.ref_name }}" >> $GITHUB_ENV
      shell: bash
