name: CI

on:
  push:
    branches: [dev]
#    paths-ignore: 
#      - '.github/workflows/**'
    tags:
      - 'v*'
      - 'rc-*'
  pull_request:
    branches: [release, main]
       name: Get new tag
       uses: ./.github/workflows/get-new-tag

     # Build the Docker image with tag for google container registry
     - name: Build
       run: |-
         docker build \
           --tag "gcr.io/$PROJECT_ID/$IMAGE:$IMAGE_TAG" \
           --build-arg GITHUB_SHA="$GITHUB_SHA" \
           --build-arg GITHUB_REF="$GITHUB_REF" \

# After successful build add tag
      - name: Update release number
        if: ${{ github.base_ref == 'main' || github.base_ref == 'release' }}
        run: |-
          git tag $IMAGE_TAG && git push --tags